version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: karmabot
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Uncomment and configure if you need Redis
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 5

volumes:
  # redis_data:
  #   driver: local
