# Force Python build on Railway/Nixpacks and install dependencies

providers = ["python"]

[phases.setup]
# Ensure Python 3.11 and build essentials are available
nixPkgs = ["python311", "pip", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

# Start command is defined in railway.toml (start.sh)
