# Force Python build on Railway/Nixpacks and install dependencies

providers = ["python"]

[phases.install]
cmds = [
  "(python3 -m ensurepip --upgrade || python -m ensurepip --upgrade || true)",
  "(python3 -m pip install --upgrade pip || python -m pip install --upgrade pip)",
  "(python3 -m pip install -r requirements.txt || python -m pip install -r requirements.txt)"
]

# Start command is defined in railway.toml (start.sh)
