# Force Python build on Railway/Nixpacks and install dependencies

providers = ["python"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

# Start command is defined in railway.toml (start.sh)
