[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -lc 'python3 main_v2.py & BOT_PID=$!; python3 -m uvicorn web.main:app --host 0.0.0.0 --port ${PORT:-8080} --proxy-headers --forwarded-allow-ips="*" --timeout-keep-alive 30 & WEB_PID=$!; while kill -0 $BOT_PID 2>/dev/null && kill -0 $WEB_PID 2>/dev/null; do sleep 1; done; if ! kill -0 $BOT_PID 2>/dev/null; then wait $BOT_PID; S=$?; echo Bot exited:$S; kill $WEB_PID 2>/dev/null || true; wait $WEB_PID || true; exit $S; else wait $WEB_PID; S=$?; echo Web exited:$S; kill $BOT_PID 2>/dev/null || true; wait $BOT_PID || true; exit $S; fi'"
healthcheckPath = "/api/health"
healthcheckTimeout = 60

[build.arguments]
# Install system dependencies
install_commands = [
    "apt-get update && apt-get install -y --no-install-recommends gcc python3-dev",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[env]
# Python Configuration
PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONFAULTHANDLER = "1"

# Application Settings
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"

# Database Configuration
DATABASE_URL = "${DATABASE_URL}"

# Web Server Configuration
WEB_CONCURRENCY = "2"
WORKERS_PER_CORE = "1"
HOST = "0.0.0.0"
PORT = "${PORT:-8080}"

# Security
SECRET_KEY = "${SECRET_KEY:-your-secret-key-here}"

# Monitoring
SENTRY_DSN = "${SENTRY_DSN}"

# Bot Configuration
BOT_TOKEN = "${BOT_TOKEN}"
ADMIN_ID = "${ADMIN_ID}"
DISABLE_POLLING = "0"

[healthcheck]
interval = 30
timeout = 10
retries = 3
start_period = 60

[checks]
# Additional health checks can be configured here
# Example:
# [checks.api]
# command = ["curl", "-f", "http://localhost:${PORT}/api/health"]
# interval = "30s"
# timeout = "5s"
# retries = 3
