[build]
builder = "nixpacks"

[deploy]
startCommand = "python main_v2.py"

[environments.production.services.bot]
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.bot"

[environments.production.services.odoo]
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile.odoo"