[build]
builder = "nixpacks"

[deploy] 
startCommand = "python main_v2.py"

[environments.production.services.WebBot]
build.builder = "nixpacks"
deploy.startCommand = "python main_v2.py"

[environments.production.services.Odoo]
build.builder = "dockerfile"
build.dockerfilePath = "Dockerfile"