[[services]]
name = "bot"
source = "."

[services.build]
builder = "nixpacks"

[services.deploy]
startCommand = "python main_v2.py"

[[services]]
name = "odoo"
source = "."

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"