[build]
builder = "nixpacks"

[deploy]
# Run both web and bot in the same container, exit if either fails
startCommand = "sh -lc 'set -e; python3 main_v2.py & python3 -m uvicorn web.main:app --host 0.0.0.0 --port ${PORT:-8080} & wait -n'"
healthcheckPath = "/health"
healthcheckTimeout = 300000

[env]
PYTHON_VERSION = "3.11"
DISABLE_POLLING = "0"

# Note: BOT_TOKEN and other sensitive variables should be set in Railway secrets
# DISABLE_POLLING can be set to "1" to disable the bot temporarily
