[build]
builder = "dockerfile"

[deploy]
startCommand = "sh -c 'uvicorn web.main:app --host 0.0.0.0 --port ${PORT:-8080}'"
healthcheckPath = "/health"
healthcheckTimeout = 300000

[env]
DISABLE_POLLING = "1"
# PYTHON_VERSION can stay if already present
