[build]
builder = "nixpacks"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "python main_v2.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8000"
HOST = "0.0.0.0"