[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -lc 'python3 main_v2.py & BOT_PID=$!; python3 -m uvicorn web.main:app --host 0.0.0.0 --port ${PORT:-8080} & WEB_PID=$!; while kill -0 $BOT_PID 2>/dev/null && kill -0 $WEB_PID 2>/dev/null; do sleep 1; done; if ! kill -0 $BOT_PID 2>/dev/null; then wait $BOT_PID; S=$?; echo Bot exited:$S; kill $WEB_PID 2>/dev/null || true; wait $WEB_PID || true; exit $S; else wait $WEB_PID; S=$?; echo Web exited:$S; kill $BOT_PID 2>/dev/null || true; wait $BOT_PID || true; exit $S; fi'"
healthcheckPath = "/health"
healthcheckTimeout = 300000

[env]
PYTHON_VERSION = "3.11"
DISABLE_POLLING = "0"

# Note: BOT_TOKEN and other sensitive variables should be set in Railway secrets
# DISABLE_POLLING can be set to "1" to disable the bot temporarily
