FROM odoo:17.0
USER root
COPY docker-entrypoint.sh /usr/local/bin/
COPY odoo-addons/ /mnt/extra-addons/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN chown -R odoo:odoo /mnt/extra-addons/
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
USER odoo
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
